const fs = require('fs');
const path = require('path');
const https = require('https');

const sarifPath = process.argv[2] || 'results.sarif';
const reportPath = process.argv[3] || 'security-report.md';
const openAiKey = process.env.OPENAI_API_KEY;
const openAiModel = process.env.OPENAI_MODEL || 'gpt-4o-mini';

function loadSarif(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`SARIF file not found: ${filePath}`);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function summarizeFindings(results) {
  const severityOrder = ['error', 'warning', 'note', 'none'];
  const severityCounts = results.reduce((acc, item) => {
    const severity = (item.level || item.kind || 'warning').toLowerCase();
    acc[severity] = (acc[severity] || 0) + 1;
    return acc;
  }, {});

  const byRule = results.reduce((acc, item) => {
    const ruleId = item.ruleId || 'unknown';
    acc[ruleId] = acc[ruleId] || { count: 0, message: [] };
    acc[ruleId].count += 1;
    if (item.message && item.message.text) acc[ruleId].message.push(item.message.text);
    return acc;
  }, {});

  return { severityCounts, byRule };
}

function formatReport(sarif, summary, topFindings) {
  const totalFindings = topFindings.length;
  const severityLines = Object.entries(summary.severityCounts)
    .sort(([a], [b]) => severityOrder.indexOf(a) - severityOrder.indexOf(b))
    .map(([level, count]) => `- **${level}**: ${count}`)
    .join('\n');

  const findingLines = topFindings.map((item, index) => {
    const location = item.locations && item.locations[0] && item.locations[0].physicalLocation;
    const file = location && location.artifactLocation && location.artifactLocation.uri;
    const region = location && location.region;
    const line = region ? region.startLine : 'N/A';
    return [`### Finding ${index + 1}`,
      `- **Rule**: ${item.ruleId || 'unknown'}`,
      `- **Severity**: ${item.level || item.kind || 'warning'}`,
      `- **Message**: ${item.message && item.message.text ? item.message.text : 'N/A'}`,
      `- **Location**: ${file || 'unknown'}:${line}`,
      ''].join('\n');
  }).join('\n');

  return [`# Security Report`,
    '',
    `## Summary`,
    '',
    `- Total findings: **${totalFindings}**`,
    severityLines ? `\n${severityLines}` : '',
    '',
    `## Top Findings`,
    '',
    findingLines || 'No findings detected.',
    '',
    `## Review Notes`,
    '',
    `The report was generated automatically by the GitHub Actions DevSecOps pipeline.`,
    openAiKey ? `An LLM review was requested and its analysis is included below.` : `LLM review was skipped because OPENAI_API_KEY is not configured.`,
    '',
    `---`,
    '',
    `*Generated by the DevSecOps pipeline.*`].join('\n');
}

function extractTopFindings(results, max = 8) {
  return results.slice(0, max);
}

async function callOpenAI(prompt) {
  const body = JSON.stringify({
    model: openAiModel,
    messages: [{ role: 'system', content: 'Você é um assistente de segurança de software. Revise os resultados SARIF e gere um resumo conciso com risco, gravidade e recomendações.' },
               { role: 'user', content: prompt }],
    max_tokens: 500,
    temperature: 0.2
  });

  const options = {
    hostname: 'api.openai.com',
    path: '/v1/chat/completions',
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${openAiKey}`,
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(body)
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          try {
            const json = JSON.parse(data);
            const content = json.choices && json.choices[0] && json.choices[0].message && json.choices[0].message.content;
            resolve(content || 'LLM review completed but no content was returned.');
          } catch (error) {
            reject(new Error(`Falha ao analisar retorno do OpenAI: ${error.message}`));
          }
        } else {
          reject(new Error(`OpenAI API error ${res.statusCode}: ${data}`));
        }
      });
    });

    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function main() {
  const sarif = loadSarif(sarifPath);
  const results = (sarif.runs || []).flatMap(run => run.results || []);
  const summary = summarizeFindings(results);
  const topFindings = extractTopFindings(results);
  let report = formatReport(sarif, summary, topFindings);

  if (openAiKey && results.length > 0) {
    const prompt = `Aqui estão os ${results.length} resultados SARIF mais importantes. Forneça um resumo de risco, explique os impactos e indique ações corretivas relevantes. Exiba como listas claras e concisas. \n\n` +
      topFindings.map((item, index) => {
        const location = item.locations && item.locations[0] && item.locations[0].physicalLocation;
        const file = location && location.artifactLocation && location.artifactLocation.uri;
        const region = location && location.region;
        const line = region ? region.startLine : 'N/A';
        return `${index + 1}. Rule: ${item.ruleId || 'unknown'}; Severity: ${item.level || item.kind || 'warning'}; File: ${file || 'unknown'}:${line}; Message: ${item.message && item.message.text ? item.message.text : 'N/A'}`;
      }).join('\n');

    try {
      const llmReview = await callOpenAI(prompt);
      report += '\n\n## LLM Review\n\n' + llmReview + '\n';
    } catch (error) {
      report += `\n\n## LLM Review\n\nFalha ao obter análise LLM: ${error.message}\n`;
    }
  }

  fs.writeFileSync(reportPath, report, 'utf8');
  console.log(`Security report written to ${reportPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
